version: "3"

services:
  db:
    image: "mariadb:10.5.8"
    restart: always
    container_name: "mysql"
    ports:
      - "3306:3306"
    volumes:
      - /etc/localtime:/etc/localtime
      - $HOME/docker/mysql/data:/var/lib/mysql
      - ./initdb.d:/docker-entrypoint-initdb.d
    environment:
      TIME_ZONE: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: "root"
    networks:
      - db

networks:
  db:
    external: true
