version: "3"

services:
  redis:
    image: "redis:6.0.9-alpine"
    container_name: "redis"
    command: "redis-server /etc/redis/redis.conf --requirepass root"
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
      - $HOME/docker/redis/data:/data
    environment:
      - TZ=Asia/Shanghai
