version: "3"

services:
  prometheus:
    image: "prom/prometheus:v2.22.1"
    container_name: prometheus
    hostname: prometheus
    restart: always
    volumes:
      - ./conf/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./conf/node_down.yml:/etc/prometheus/node_down.yml
    ports:
      - "9090:9090"
    networks:
      - monitor

  altermanager:
    image: "prom/alertmanager:v0.21.0"
    container_name: alertmanager
    hostname: alertmanager
    restart: always
    volumes:
      - ./conf/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"
    networks:
      - monitor

  grafana:
    image: "grafana/grafana:7.3.2"
    container_name: grafana
    hostname: grafana
    restart: always
    ports:
      - "3000:3000"
    networks:
      - monitor

  node-exporter:
    image: "prom/node-exporter:v1.0.1"
    container_name: node-exporter
    hostname: node-exporter
    restart: always
    ports:
      - "9100:9100"
    networks:
      - monitor

  cadvisor:
    image: "google/cadvisor:v0.33.0"
    container_name: cadvisor
    hostname: cadvisor
    ports:
      - "18080:8080"
    networks:
      - monitor

networks:
  monitor:
    external: true
